### ISSUE TITLE
Ottoman sync_gateway _type field incompatibility update

### ISSUE THREAD

**Issue by jnkroeker** [moxious/ottoman-contributions#1]
Hey there,

My team is facing this same issue. Judging by the lack of activity on the cb forum thread, it seems that there is no official fix coming soon. Would you mind sharing your hack with the community?

Cheers,

J

**Comment by moxious** [comment]
It's been a while.  Let me see if I can find the colleague that did this, I'll have him post something if he can find it (the hack).

There is this separate thread - https://github.com/couchbaselabs/node-ottoman/issues/79  you might want to check it, Brett is the maintainer.

From my perspective, changing this _type incompatibility is not actually that big of a deal.  For Brett though I think it's important to maintain backwards compatibility.   I'm not sure if this is the cleanest solution, but a solution would be for Ottoman to keep using _type, but when you create the ottoman singleton, provide a parameter you could use to globally rename which field should be used instead of _type.   This would be a fiddly change, but I'm guessing it would only be an afternoon's worth of work.   Getting consensus on how best to address this may be more difficult than actually putting the fix in.  Unfortunately while I've contributed a fair bit to ottoman via PRs, I don't have visibility into all of the things that must be protected in this kind of change.

But you're not the first, second, or third person to ask for this.   Head on over to that ottoman issue page, add your voice there too that this is a priority.

**Comment by jnkroeker** [comment]
Much appreciated!
